#!/bin/bash
#SBATCH --job-name=1_$PREFIX_$COMPOUND
#SBATCH --output=mpi_1_$PREFIX_$COMPOUND.out
#SBATCH --error=mpi_1_$PREFIX_$COMPOUND.err
#SBATCH --ntasks=$PROCESSORS
#SBATCH --time=00-16:00:00
#SBATCH --qos=$QOS_bscls

ml intel/2023.2.0
ml cmake/3.25.1
ml impi/2021.10.0
ml mkl/2023.2.0
ml miniconda/24.1.2

export PELE=/gpfs/projects/bsc72/PELE++/mnv/1.8.1b1
export PELELIC=/gpfs/projects/bsc72/PELE++/license
export SCHRODINGER=/gpfs/projects/bsc72/Programs/SCHRODINGER_ACADEMIC
export USESRUN=1

eval "$(conda shell.bash hook)"
source activate /gpfs/projects/bsc72/conda_envs/nbdsuite/0.5.0

python -u -m nbdsuite.main $OUTDIR/results/$COMPOUND.yaml

#python $REPO/scripts/recover_connectivity.py $OUTDIR/results/$COMPOUND/2_pele_pdb_preprocessor/complexes/complex_2_ligand.pdb --pdb_target $OUTDIR/results/$COMPOUND/4_adaptive_pele_simulation/complex_2/output/topologies/topology_0.pdb -lc L -lt L
