#!/bin/bash
#SBATCH --job-name=$OUTNAME_$COMPOUND
#SBATCH --output=mpi_$OUTNAME_$COMPOUND.out
#SBATCH --error=mpi_$OUTNAME_$COMPOUND.err
#SBATCH --ntasks=1
#SBATCH --time=00-1:00:00
#SBATCH --qos=bsc_ls

module purge
module load ANACONDA/2019.10
module load intel mkl impi gcc # 2> /dev/null
module load impi
module load boost/1.64.0

eval "$(conda shell.bash hook)"

conda activate /gpfs/projects/bsc72/conda_envs/platform/1.6.3

python -m pele_platform.main $CURRENT/results/$OUTNAME/$COMPOUND.yaml
