#!/bin/bash
#SBATCH --job-name=1_$OUTNAME_$COMPOUND
#SBATCH --output=mpi_1_$OUTNAME_$COMPOUND.out
#SBATCH --error=mpi_1_$OUTNAME_$COMPOUND.err
#SBATCH --ntasks=$PROCESSORS
#SBATCH --time=00-8:00:00
#SBATCH --qos=gp_bscls

module purge
module load anaconda
module load intel mkl impi cmake
module load transfer
module load bsc

eval "$(conda shell.bash hook)"
source activate /gpfs/projects/bsc72/conda_envs/platform

python -m pele_platform.main $CURRENT/results/$OUTNAME/$COMPOUND.yaml

#python $CURRENT/scripts/generate_results.py --workDIR $CURRENT/results/$OUTNAME/$COMPOUND

python $CURRENT/scripts/recover_connectivity.py $CURRENT/$LIGSDIR/$COMPOUND_prep.pdb --pdb_target $CURRENT/results/$OUTNAME/$COMPOUND/output/topologies/topology_0.pdb -lc L -lt L

#python /gpfs/projects/bsc72/COVID/COVID_VS_analysis/HBCounter.py $CURRENT/results/$OUTNAME/$COMPOUND/ -r report -n $PROCESSORS -t output/topologies/topology_0.pdb -o hbonds.out
