#!/bin/bash
#SBATCH --job-name=3_$PREFIX_$COMPOUND
#SBATCH --output=mpi_3_$PREFIX_$COMPOUND.out
#SBATCH --error=mpi_3_$PREFIX_$COMPOUND.err
#SBATCH --ntasks=1
#SBATCH --time=00-2:00:00
#SBATCH --qos=$QOS_bscls

module purge
module load anaconda
module load intel mkl impi cmake
module load transfer
module load bsc

eval "$(conda shell.bash hook)"
source activate /gpfs/projects/bsc72/conda_envs/PELE_ConStraParl

python $REPO/scripts/disc.py -d $OUTDIR/results/$COMPOUND_min/output/ -c 4
python $REPO/scripts/corrector.py -d $OUTDIR/results/$COMPOUND/4_adaptive_pele_simulation/complex_2 -lf $OUTDIR/results/$COMPOUND_min --skip_strain_per_cluster
