#!/bin/bash
#SBATCH --job-name=0_$OUTNAME_$COMPOUND
#SBATCH --output=mpi_0_$OUTNAME_$COMPOUND.out
#SBATCH --error=mpi_0_$OUTNAME_$COMPOUND.err
#SBATCH --ntasks=1
#SBATCH --time=00-1:00:00
#SBATCH --qos=$QOS_bscls

module purge
module load anaconda
module load intel mkl impi cmake
module load transfer
module load bsc

eval "$(conda shell.bash hook)"
source activate /gpfs/projects/bsc72/conda_envs/platform

python -m pele_platform.main $CURRENT/results/$OUTNAME/$COMPOUND.yaml
